name: Deploy website on push
on: 
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do repositorio
      uses: actions/checkout@v2
    - name: Deploy para meu hosting
      uses: appleboy/ssh-action@main
      env:
        key: ${{ secrets.SERVER_SSH_KEY }}
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        #ARGS: "-rltgoDzvO --delete"
        #REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
        #TARGET: ${{ secrets.REMOTE_TARGET }}
        script: |
          cd /var/www/html/
          git checkout -f 
          git pull
        